spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/todo
    username: root
    password: green502

# mybatis config
mybatis:
  type-aliases-package: com.green.todoapp
  mapper-locations: mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/todo/

server:
  port: 8081
